---
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '44 4 * * 0'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    name: RT ${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - '4.2'
          - '4.4'
          - '5.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Hub metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: netsandbox/request-tracker
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=latest,enable=${{ matrix.version == '5.0' }}

      - name: Extract GitHub Container Registry metadata
        id: meta_ghcr
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/request-tracker
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=latest,enable=${{ matrix.version == '5.0' }}

      - name: Build and push Docker Hub
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.version }}/
          file: ${{ matrix.version }}/Dockerfile
          no-cache: true
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push GitHub Container Registry
        id: build-and-push-ghcr
        uses: docker/build-push-action@v3
        with:
          build-args: IMAGE=ghcr.io/netsandbox/request-tracker-base
          context: ${{ matrix.version }}/
          file: ${{ matrix.version }}/Dockerfile
          no-cache: true
          pull: true
          push: true
          tags: ${{ steps.meta_ghcr.outputs.tags }}
          labels: ${{ steps.meta_ghcr.outputs.labels }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v2

      - name: Sign the published Docker Hub images
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: true

      - name: Sign the published GitHub Container Registry images
        run: echo "${{ steps.meta_ghcr.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push-ghcr.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: true

      - uses: actions/delete-package-versions@v4
        if: ${{ matrix.version == '5.0' }}
        with:
          package-name: request-tracker
          package-type: container
          min-versions-to-keep: 30
