name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '44 4 * * 0'

jobs:
  main:
    name: RT ${{ matrix.rt }} Tag ${{ matrix.tag }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - rt: '4.2'
            tag: '4.2'
          - rt: '4.4'
            tag: '4.4'
          - rt: '5.0'
            tag: '5.0'
          - rt: '5.0'
            tag: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push RT ${{ matrix.rt }} Tag ${{ matrix.tag }} Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.rt }}/
          file: ${{ matrix.rt }}/Dockerfile
          no-cache: true
          pull: true
          push: true
          tags: netsandbox/request-tracker:${{ matrix.tag }}

      - name: Build and push RT ${{ matrix.rt }} Tag ${{ matrix.tag }} GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          build-args: IMAGE=ghcr.io/netsandbox/request-tracker-base
          context: ${{ matrix.rt }}/
          file: ${{ matrix.rt }}/Dockerfile
          no-cache: true
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/request-tracker:${{ matrix.tag }}
